name: Selenium Test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies with poetry
      run: |
        poetry install

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: 135
        install-chromedriver: true
        install-dependencies: true

    - name: Run script
      run: poetry run python test.py
      env:
        CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
    - name: Upload csv files
      uses: actions/upload-artifact@v4
      with:
        name: stock-weights
        path: stock_weights/
    - name: Upload debug HTML if available
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: timeout-debug
        path: timeout_debug.html
