name: Selenium Test

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies with poetry
      run: |
        poetry install

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run script
      run: python main.py

    - name: Upload debug HTML if available
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: timeout-debug
        path: timeout_debug.html
